// account
export const LOGIN_ACCOUNT_REQUEST = 'LOGIN_ACCOUNT_REQUEST';
export const LOGIN_ACCOUNT_SUCCESS = 'LOGIN_ACCOUNT_SUCCESS';
export const LOGIN_ACCOUNT_REJECTED = 'LOGIN_ACCOUNT_REJECTED';

//notify
export const SHOW_ERROR = 'SHOW_ERROR';
export const SHOW_SUCCESS = 'SHOW_SUCCESS';
export const SHOW_WARNING = 'SHOW_WARNING';
export const RESET_NOTIFY = 'RESET_NOTIFY';

//fight
export const GET_FIGHTS_REQUEST = 'GET_FIGHTS_REQUEST';
export const GET_FIGHTS_SUCCESS = 'GET_FIGHTS_SUCCESS';
export const GET_FIGHTS_REJECTED = 'GET_FIGHTS_REJECTED';
export const GET_FIGHT_DETAILS_REQUEST = 'GET_FIGHT_DETAILS_REQUEST';
export const GET_FIGHT_DETAILS_SUCCESS = 'GET_FIGHT_DETAILS_SUCCESS';
export const GET_FIGHT_DETAILS_REJECTED = 'GET_FIGHT_DETAILS_REJECTED';

//socket
export const WEBSOCKET_CONNECT = 'WEBSOCKET_CONNECT';
export const WEBSOCKET_SEND_MESSAGE = 'WEBSOCKET_SEND_MESSAGE';
export const WEBSOCKET_RECEIVED_MESSAGE = 'WEBSOCKET_RECEIVED_MESSAGE';